author: "Alexey Karapetov <karapetov@gmail.com>"
description: "JSON:API v1.0 (http://jsonapi.org) Document Model and Parser"
homepage: "https://github.com/f3ath/json-api-document-dart"
name: "json_api_document"
version: "1,0.0-beta.1"
dev_dependencies:
  json_matcher: "^0.2.3"
  test: "^1.6.1"
environment: 
  sdk: ">=2.0.0 <3.0.0"
