author: "Alexey Karapetov <karapetov@gmail.com>"
description: "JSON API (or jsonapi, see http://jsonapi.org) implementation in Dart2. Builds JSON API v0.1 Documents according to the standard."
homepage: "https://github.com/f3ath/json-api-dart"
name: "json_api_document"
version: "0.3.3"
dev_dependencies: 
  json_matcher: ">=0.2.2"
  pubspec_version: "^0.1.0"
  test: "1.3.0"
environment: 
  sdk: ">=2.0.0 <3.0.0"
